In [24]:
import numpy as np

k = np.linspace(- np.pi, np.pi, 51)
n = np.arange(-1, 2)
G = 2*np.pi*n
alpha = 1

lmbda = lambda k: np.abs(k - G)**2

In [19]:
G

array([-6.28318531,  0.        ,  6.28318531])

In [23]:
lmbda(0.2)

array([4.20316917e+01, 4.00000000e-02, 3.70051435e+01])

In [12]:
n

array([-1,  0,  1])

In [ ]:
def hamiltoniano(k, G, n, alpha):
    """
    Hamiltonian for the system.
    
    Parameters:
    k : float
        Wave vector.
    G : array_like
        Reciprocal lattice vectors.
    n : array_like
        Integer indices.
    alpha : float
        Parameter related to the system.
        
    Returns:
    H : array_like
        Hamiltonian matrix.
    """
    H = np.zeros((len(n), len(n)), dtype=complex)
    
    for i, ni in enumerate(n):
        for j, nj in enumerate(n):
            H[i, j] = alpha * np.exp(-1j * (k + G[ni - nj]))
    
    return H

In [28]:
lmbda_lista = []

for ki in k:
    lmbda_i = np.abs(ki - G)**2
    lmbda_lista.append(lmbda_i)

lmbda_lista = np.array(lmbda_lista)
lmbda_lista

array([[9.86960440e+00, 9.86960440e+00, 8.88264396e+01],
       [1.06749641e+01, 9.09582742e+00, 8.64735259e+01],
       [1.15119066e+01, 8.35363317e+00, 8.41521950e+01],
       [1.23804318e+01, 7.64302165e+00, 8.18624467e+01],
       [1.32805397e+01, 6.96399287e+00, 7.96042813e+01],
       [1.42122303e+01, 6.31654682e+00, 7.73776985e+01],
       [1.51755037e+01, 5.70068350e+00, 7.51826985e+01],
       [1.61703599e+01, 5.11640292e+00, 7.30192812e+01],
       [1.71967987e+01, 4.56370508e+00, 7.08874467e+01],
       [1.82548203e+01, 4.04258996e+00, 6.87871948e+01],
       [1.93444246e+01, 3.55305758e+00, 6.67185258e+01],
       [2.04656117e+01, 3.09510794e+00, 6.46814394e+01],
       [2.16183815e+01, 2.66874103e+00, 6.26759358e+01],
       [2.28027340e+01, 2.27395685e+00, 6.07020149e+01],
       [2.40186693e+01, 1.91075541e+00, 5.87596768e+01],
       [2.52661873e+01, 1.57913670e+00, 5.68489214e+01],
       [2.65452880e+01, 1.27910073e+00, 5.49697487e+01],
       [2.78559715e+01, 1.01064

In [29]:
vetor = np.diag(lmbda_lista)
vetor

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


array([ 9.8696044 ,  9.09582742, 84.15219497])

In [ ]:
matriz = np.diag